# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Calculate C-index (consistency index)
#' @description Calculate C-index (consistency index)
#' @param data_1 data in matrix form
#' @param beta_6 the estimator that has been obtained from AFT model
#' @return Returns a number between 0-1
#' @examples
#' \dontrun{
#'     result <- computeCindex(as.numeric(beta_0), as.matrix(data_r))
#' }
#' @export
computeCindex <- function(beta_6, data_1) {
    .Call('_SA23229012_computeCindex', PACKAGE = 'SA23229012', beta_6, data_1)
}

